import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Header } from "@/widgets/header";
import { Provider } from "react-redux";
import { ThemeClient } from "@/shared/ui";
import '@/shared/styles/globals.css'
import { store } from "@/shared/config/store";

const roboto = Roboto({
  weight: ["400", "100", "300", "500", "700", "900"],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ThemeClient>
          <Header />
          {children}
        </ThemeClient>
      </body>
    </html>
  );
}
